import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { FaAngleRight, FaArrowRight, FaClock, FaDollarSign, FaFacebookF, FaInstagram, FaMapMarkerAlt, FaPlane, FaStar, FaUser, FaYoutube } from "react-icons/fa";
import { IoIosCall } from "react-icons/io";
import { AiOutlineMenu } from "react-icons/ai";
import { IoLocationSharp, IoMailOpen, IoPeopleSharp } from "react-icons/io5";
import { TbTimeDuration30, TbTimeDuration5, TbWorld } from "react-icons/tb";
import { FaXTwitter } from "react-icons/fa6";
import { GiDuration } from "react-icons/gi";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isFlagSet, setIsFlagSet] = useState(false);

  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 5
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 4
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 3
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1
    }
  };

  const responsivereviews = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 4
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1
    }
  };

  useEffect(() => {
    const timerId = setTimeout(() => {
      setIsFlagSet(true);
    }, 2000);

    // Cleanup function to clear the timer in case the component unmounts before 3 seconds
    return () => clearTimeout(timerId);
  }, []);

  return (
    <>
      {isFlagSet != false ?
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className='col-md-12' >
            <div className='col-md-12'>
              <button className='btn btn-success rounded-circle button_position_whats'>WW</button>
            </div>
            <div className='col-md-12 menu_mob py-2 px-3'>
              <div className='row bg-white '>
                <div className='col-md-6 col-6 m-auto'>
                  <h1 className='text-green m-0 p-0'><b> Tourist</b></h1>
                </div>
                <div className='col-md-6 col-6 text-end'>
                  <button className='btn btn-success button_green'><AiOutlineMenu /></button>
                </div>
              </div>
            </div>

            {/* Header one ---------------------------------------------------------- */}
            <div className='col-md-12 background_header1 px-4'>
              <div className='row py-2'>
                <div className='col-md-6 m-auto'>
                  <div className='flex_using_head'>
                    <p className='m-0 p-0'> <FaMapMarkerAlt /> <small>123 Street, New York, USA</small>
                    </p>
                    <p className='m-0 p-0 ps-md-3'> <IoIosCall /> <small>123 Street, New York, USA</small>
                    </p>
                    <p className='m-0 p-0 ps-md-3'> <IoMailOpen /> <small>123 Street, New York, USA</small>
                    </p>
                  </div>
                </div>
                <div className='col-md-6 text-end'>
                  <span><button className='btn btn-outline-light btn-sm rounded-circle'><FaFacebookF /></button></span>
                  <span><button className='btn btn-outline-light btn-sm ms-md-2 rounded-circle'><FaInstagram /></button></span>
                  <span><button className='btn btn-outline-light btn-sm ms-md-2 rounded-circle'><FaYoutube /></button></span>
                  <span><button className='btn btn-outline-light btn-sm ms-md-2 rounded-circle'><FaXTwitter /></button></span>
                </div>
              </div>
            </div>

            {/* Header 2 ------------------------------------------------------------- */}



            <div className='col-md-12 position_parent_hero'>
              <div className='col-md-12 position_child'>
                <video loop autoPlay muted className="vedioPlayer">
                  <source
                    src="/video/jetskiu.mp4"
                    type="video/mp4"
                  />
                </video>
              </div>
              <div className='col-md-12 position_new pt-2'>
                <div className='col-md-12 header_2 px-4'>
                  <div className='row'>
                    <div className='col-md-5'>
                      <h1 className='text-green'>SunAndSeaJetskiDubai</h1>
                    </div>
                    <div className='col-md-7 pt-2'>
                      <div className='col-md-12 flex_using_head_j'>
                        <p className='font_set_new mt-2'>Home</p>
                        <p className='font_set_new mt-2'>Aboutus</p>
                        <p className='font_set_new mt-2'>Services</p>
                        <p className='font_set_new mt-2'>Packages</p>
                        <p className='font_set_new mt-2'>Pages</p>
                        <p className='font_set_new mt-2'>Contactus</p>
                        {/* <p className='font_set_new'>
                      <button className='btn btn-success px-4 button_green rounded-pill'> Register </button>
                    </p> */}
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-12  pb-3 pt-2'>
                  <div className='col-md-12 text-center padding_custom_top'>
                    <h1 className='color_white_new'>Enjoy Your Vacation With Us</h1>
                    <p className="fs-4 text-white mb-4 animated slideInDown">Tempor erat elitr rebum at clita diam amet diam et eos erat ipsum lorem sit</p>
                  </div>

                </div>
              </div>
            </div>


            <div className='col-md-12 padding_left_right_custom paddin_top_other mb-5 margin-top_custom pb-4'>
              <div className='row'>
                <div className='col-md-6 mt-md-0 mt-4'>
                  <img class="img-fluid img_width_set" src="/img/new.jpeg" />
                </div>
                <div className='col-md-6 mt-4 m-md-auto'>
                  <h1 className='section_1_t'><b>About <span className='text-green'>Us</span></b></h1>
                  <p>

                    Welcome to SunAndSeaJetSkiDubai, your premier destination for thrilling jet ski adventures in the heart of Dubai, UAE. Nestled against the backdrop of the iconic skyline, our passion for adventure and water sports comes alive as we offer an exhilarating experience for both seasoned riders and beginners.
                  </p>
                  <p>
                    <b> SunAndSeaJetSkiDubai,</b> safety is paramount – our certified staff ensures thorough briefings and top-of-the-line jet skis to guarantee a secure and high-performance ride. With customizable packages, breathtaking views, and exceptional customer service, we create memories that last a lifetime. Whether you're seeking solo excitement or planning a group or corporate event, SunAndSeaJetSkiDubai invites you to dive into the ultimate aquatic adventure, booking your unforgettable ride against the stunning Dubai waters.
                  </p>
                  {/* <div className='row'>
                <div className='col-md-6'>
                  <p className='mb-1' ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1'  ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1' ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1'  ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                </div>
                <div className='col-md-6'>
                  <p className='mb-1' ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1'  ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1' ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                  <p className='mb-1'  ><FaArrowRight className='text-green' />&nbsp; First Class Flights</p>
                </div>
              </div> */}
                  {/* <div className='btn btn-success button_green px-5 py-3 mt-md-1 mt-3'>
                Read More
              </div> */}
                </div>
              </div>
            </div>
            {/* <div className='col-md-12 text-center'>
          <h1 className='section_1_t'><b>Our Services</b></h1>
        </div>
        <div className='col-md-12 padding_left_right_custom mb-5 pb-4 mt-5'>
          <div className='row'>
            <div className='col-md-3  mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
          </div>
          <div className='row mt-4'>
            <div className='col-md-3  mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
            <div className='col-md-3 mt-4 mt-md-0'>
              <div className='col-md-12 service-item px-3 py-3'>
                <TbWorld className='fa-3x' />
                <h5 className='mt-3 ps-1 text_color_word_C'>WorldWide Tours</h5>
                <p className='ps-1'>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
              </div>
            </div>
          </div>
        </div> */}
            <div className='col-md-12 text-center'>
              <h1 className='section_1_t'><b>Our Gallary</b></h1>
            </div>
            <div className='col-md-12 padding_left_right_custom mb-5 pb-4 mt-5'>
              <Carousel responsive={responsive}
                autoPlay={true}
                keyBoardControl={true}
                infinite={true}
                autoPlaySpeed={2000}>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g2.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g3.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g5.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g7.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g8.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g9.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g10.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g11.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g12.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g13.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g14.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g15.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g16.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g17.jpeg' />
                  </div>
                </div>
                <div className='px-3'>
                  <div className='col-md-12'>
                    <img className='img-fluid img_border_rad' src='/img/g18.jpeg' />
                  </div>
                </div>

              </Carousel>

            </div>
            <div className='col-md-12 text-center'>
              <h1 className='section_1_t'><b>Awesome Packages</b></h1>
            </div>
            <div className='col-md-12  mt-5 mb-5 pb-4 padding_left_right_custom'>
              <div className='row'>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  Burj AL arab</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />  9am to 1pm</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><TbTimeDuration30 className='text-green' />30 minutes</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 300<span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          30 minutes jetski tour<br /> burj AL arab.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />  9am to 1pm</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' /> 60 minutes</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 450<span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          60 minutes jetski tour burj AL arab and<br /> atlantis.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />  9am to 1pm</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' /> 120 minutes</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 900 <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          120 minutes jetski tour burj AL arab, atlantis and blue water dubai eye jb
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' />30 minutes</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 300 <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          30 minutes jetski tour
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' />60 minutes </small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 500  <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          60 minutes jetski tour
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' />120 minutes </small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 1000  <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          120 minutes jetski tour
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' />20 minutes </small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 600  <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          20 minutes jetcar tour
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' />30 minutes </small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 800  <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          30 minutes jetcar tour
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className='col-md-4 mt-md-0 '>
                  <div className='col-md-12  pb-4 parent_div'>
                    <div className='col-md-12'>
                      <img className='img-fluid img_border_topr' src='/img/p1.jpg' />
                    </div>
                    <div className='col-md-12 bprder_new_r pb-4'>
                      <div className='col-md-12 px-2'>
                        <div className='row px-1 '>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><IoLocationSharp className='text-green' />  burj AL arab </small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><FaClock className='text-green' />1pm to sunset</small>
                            </div>
                          </div>
                          <div className='col-md-4 bprder_new py-1'>
                            <div className='col-md-12 text-center'>
                              <small><GiDuration className='text-green' /> Flyboard</small>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className='col-md-12 text-center'>
                        <h3 className='pt-4 color_new_text1 mb-0'><small className='font_size_small_from'>From</small> 300  <span className='font_size_small_from'> AED</span> </h3>
                      </div>
                      <div className='col-md-12 text-center'>
                        <span><FaStar className='text-green' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                        <span><FaStar className='text-green ms-1' /></span>
                      </div>
                      <div className='col-md-12 text-center px-3 mt-3'>
                        <p className='m-0 p-0'>
                          Flyboard for 300 aed
                        </p>
                      </div>
                    </div>
                  </div>
                </div>


              </div>
            </div>
            <div className='col-md-12 text-center'>
              <h1 className='section_1_t'><b>Customer Reviews</b></h1>
            </div>
            <div className='col-md-12 padding_left_right_custom mb-5 pb-4 mt-5'>
              <Carousel responsive={responsivereviews}
                autoPlay={true}
                keyBoardControl={true}
                infinite={true}
                autoPlaySpeed={2000}>
                <div className='px-2'>
                  <div className='col-md-12 text-center'>
                    <button className='btn btn-success m_top_n py-2 button_green_1 rounded-circle'>
                      <FaUser className='fa-4x' />
                    </button>
                  </div>
                  <div className='col-md-12 px-2 text-center border_circle'>
                    <p className='mb-0 mt-5 color_bck'>Tom Adamson</p>
                    <div className='col-md-12 text-center'>
                      <span><FaStar className='text-green' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                    </div>
                    <div className='col-md-12 text-center px-5'>
                      <hr className='line_white' />
                    </div>
                    <div className='col-md-12 pt-3 pb-2'>
                      <p> The jet skis were plenty fast for beginners and the whole experience was excellent. 10/10</p>
                    </div>
                  </div>
                </div>
                <div className='px-2'>
                  <div className='col-md-12 text-center'>
                    <button className='btn btn-success m_top_n py-2 button_green_1 rounded-circle'>
                      <FaUser className='fa-4x' />
                    </button>
                  </div>
                  <div className='col-md-12 px-2 text-center border_circle'>
                    <p className='mb-0 mt-5 color_bck'>Rajiv Shah</p>
                    <div className='col-md-12 text-center'>
                      <span><FaStar className='text-green' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                    </div>
                    <div className='col-md-12 text-center px-5'>
                      <hr className='line_white' />
                    </div>
                    <div className='col-md-12 pt-3 pb-2'>
                      <p>Easily the best priced, amazing views of the Burj Al Arab and amazing service </p>
                    </div>
                  </div>
                </div>
                <div className='px-2'>
                  <div className='col-md-12 text-center'>
                    <button className='btn btn-success m_top_n py-2 button_green_1 rounded-circle'>
                      <FaUser className='fa-4x' />
                    </button>
                  </div>
                  <div className='col-md-12 px-2 text-center border_circle'>
                    <p className='mb-0 mt-5 color_bck'>Jeffrey blok</p>
                    <div className='col-md-12 text-center'>
                      <span><FaStar className='text-green' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                    </div>
                    <div className='col-md-12 text-center px-5'>
                      <hr className='line_white' />
                    </div>
                    <div className='col-md-12 pt-3 pb-2'>
                      <p>It was a awesome experience! They had made the best Jetski experience for me!</p>
                    </div>
                  </div>
                </div>
                <div className='px-2'>
                  <div className='col-md-12 text-center'>
                    <button className='btn btn-success m_top_n py-2 button_green_1 rounded-circle'>
                      <FaUser className='fa-4x' />
                    </button>
                  </div>
                  <div className='col-md-12 px-2 text-center border_circle'>
                    <p className='mb-0 mt-5 color_bck'>Katie Edwards</p>
                    <div className='col-md-12 text-center'>
                      <span><FaStar className='text-green' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                      <span><FaStar className='text-green ms-1' /></span>
                    </div>
                    <div className='col-md-12 text-center px-5'>
                      <hr className='line_white' />
                    </div>
                    <div className='col-md-12 pt-3 pb-2'>
                      <p>Amazing! Booked it in the morning via WhatsApp and then did the parasailing in the afternoon. </p>
                    </div>
                  </div>
                </div>
              </Carousel>
            </div>
            <div className='col-md-12 text-center'>
              <h1 className='section_1_t'><b>On Google Maps</b></h1>
            </div>
            <div className="elfsight-app-3f8bce26-7b34-4501-ade2-16858a93181c" data-elfsight-app-lazy></div>
            <div className='col-md-12 padding_left_right_custom mt-5 mb-5 pb-4'>
              <iframe src="https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d15956.785608727221!2d55.18518749178701!3d25.143439188456263!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjXCsDA5JzA5LjIiTiA1NcKwMTEnNTQuMCJF!5e0!3m2!1sen!2s!4v1702723801409!5m2!1sen!2s" width="100%" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div className='col-md-12 text-center'>
              <h1 className='section_1_t'><b>Contact us</b></h1>
            </div>
            <div className='col-md-12 padding_left_right_custom mb-5 pb-4'>
              <div className='col-md-12 background_new_2 mt-5 px-md-5 px-3 py-5'>
                <div className='row'>
                  <div className='col-md-6 u_font'>
                    <h6 className='text-white'><b>Booking</b></h6>
                    <h1 className='text-white'><b>Online Booking</b></h1>
                    <p className='text-white'>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.</p>
                    <p className='text-white'>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.
                      empor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit
                    </p>
                    <p className='text-white'>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.
                      empor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit
                    </p>
                  </div>
                  <div className='col-md-6 u_font'>
                    <h1 className='text-white '><b>Book A Tour</b></h1>
                    <div className='col-md-12 mt-4'>
                      <div className='row'>
                        <div className='col-md-6'>
                          <input className='form-control input_deign form-control-lg' type='text' placeholder='Your Name' />
                        </div>
                        <div className='col-md-6 mt-md-0 mt-4'>
                          <input className='form-control input_deign form-control-lg' type='text' placeholder='Your Email' />
                        </div>
                        <div className='col-md-6 mt-4'>
                          <input className='form-control input_deign form-control-lg' type='text' placeholder='Date & Time' />
                        </div>
                        <div className='col-md-6 mt-4'>
                          <input className='form-control input_deign form-control-lg' type='text' placeholder='Destination' />
                        </div>
                        <div className='col-md-12 mt-4'>
                          <textarea className='form-control input_deign form-control-lg' type='text' placeholder='Special request' ></textarea>
                        </div>
                        <div className='col-md-12'>
                          <button className='btn btn-outline-light border_radius_n w-100 mt-4 py-3'> Book Now </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className='col-md-12 padding_left_right_custom pt-5 pb-5  bg_footer'>
              <div className='row pt-4'>
                <div className='col-md-3'>
                  <div className='col-md-12'>
                    <h4 className='text-white'><b>Company</b></h4>
                    <h6 className='text-white'><FaAngleRight />About Us</h6>
                    <h6 className='text-white'> <FaAngleRight />Our Services</h6>
                    <h6 className='text-white'> <FaAngleRight />Our Gallery</h6>
                    <h6 className='text-white'> <FaAngleRight />Awesome Packages</h6>
                    <h6 className='text-white'> <FaAngleRight />3 easy steps</h6>
                  </div>

                </div>
                <div className='col-md-3 mt-md-0 mt-3'>
                  <h4 className='text-white'><b>Contact</b></h4>
                  <h6 className='text-white'> <FaAngleRight />Contactus</h6>
                  <h6 className='text-white'> <FaAngleRight />Customer Reviews</h6>
                  <h6 className='text-white'> <FaAngleRight />Schedule</h6>
                </div>
                <div className='col-md-3 mt-md-0 mt-3'>
                  <h4 className='text-white'><b>Location</b></h4>
                  <h6 className='text-white'> <FaAngleRight />Maps</h6>
                </div>

              </div>
            </div>
          </div>
        </>
        :
        <div className='col-md-12 text-center pt-5 mt-5'>
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
        </div>
      }
    </>
  )
}
